/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-05-17 07:30:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class emphome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Employee Management</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap cdn -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- google font link -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Bitter:wght@800&family=Krona+One&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- grid css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"grid/grid.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- fontawesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/all.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- css link -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("\r\n");
      out.write("    <section id=\"title\" class=\"title\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg fixed-top\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">Rythy</a>\r\n");
      out.write("                <button class=\"navbar-toggler custom-toggler\" type=\"btn\" data-toggle=\"collapse\" data-target=\"#collapse\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"collapse\">\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#about\" class=\"nav-link\">ABOUT</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#services\" class=\"nav-link\">OUR COMPANY</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#contact\" class=\"nav-link\">CONTACT</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a href=\"login.jsp\"> <button type=\"button\" class=\"btn btn-outline-light btn1 btn-lg\">AdminLogin</button></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <!-- header content -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <h1>Welcome to Rythy</h1>\r\n");
      out.write("                    <!-- <p>Employee Management System</p> -->\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <img class=\"title-img\" src=\"img/img2.png\" alt=\"headerimg\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section id=\"about\">\r\n");
      out.write("        <h2>Our Company</h2>\r\n");
      out.write("        <div class=\"line\"></div>\r\n");
      out.write("        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. <br>Lorem ipsum dolor sit amet consectetur,\r\n");
      out.write("            adipisicing elit. Odit doloribus maiores necessitatibus molestias earum facere,\r\n");
      out.write("            ex quia adipisci voluptatem. Obcaecati reprehenderit molestiae tempore impedit quasi,\r\n");
      out.write("            distinctio neque eligendi nisi pariatur.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section id=\"services\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <h2>What we do</h2>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fab fa-java fa-3x  icon\"></i>\r\n");
      out.write("                            <h3 class=\"card-title\">JavaProgramming</h3>\r\n");
      out.write("                            <h4 class=\"card-subtitle\">web software</h4>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <img src=\"img/icons8-web-design-64.png\" class=\"img-icon\" alt=\"icon\">\r\n");
      out.write("                            <h3 class=\"card-title\">Full Stack</h3>\r\n");
      out.write("                            <h4 class=\"card-subtitle\">Responsive web Designing</h4>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-code fa-3x icon\"></i>\r\n");
      out.write("                            <h3 class=\"card-title\">Web Designing</h3>\r\n");
      out.write("                            <h4 class=\"card-subtitle\">Frame Work</h4>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-database fa-3x icon\"></i>\r\n");
      out.write("                            <h3 class=\"card-title\">Data Base</h3>\r\n");
      out.write("                            <h4 class=\"card-subtitle\">Backend</h4>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fab fa-android fa-3x icon\"></i>\r\n");
      out.write("                            <h3 class=\"card-title\">Android Development</h3>\r\n");
      out.write("                            <h4 class=\"card-subtitle\">Mobile App</h4>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-network-wired fa-3x icon\"></i>\r\n");
      out.write("                            <h3 class=\"card-title\">CCNA</h3>\r\n");
      out.write("                            <h4 class=\"card-subtitle\">Networking</h4>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section id=\"contact\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <h2>Get in touch</h2>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <center>\r\n");
      out.write("                    <form action=\"\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Name\" required>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Subject\" required>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Email\" required>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <textarea name=\"message\" id=\"message\" cols=\"30\" rows=\"6\" placeholder=\"Message\" required></textarea>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-info \" >Send Message</button>\r\n");
      out.write("                    </center>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-1\"></div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-5 contact1\">\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <p class=\"contact-p\"><i class=\"fa fa-map-marker contact-icon\"></i> &nbsp;&nbsp; 23 main street Matunga In front of railway station</p>\r\n");
      out.write("                    <p class=\"contact-p\"><i class=\"fa fa-phone contact-icon\"></i> &nbsp;&nbsp; 012-235-24810</p>\r\n");
      out.write("                    <p class=\"contact-p\"><i class=\"fa fa-envelope contact-icon\"></i> &nbsp;&nbsp; rythy@2021.com</p>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row footer\">\r\n");
      out.write("                <div class=\"col-md-4 media\">\r\n");
      out.write("                    <i class=\"fab fa-facebook-f c-icon\"></i>\r\n");
      out.write("                    <i class=\"fab fa-instagram c-icon\"></i>\r\n");
      out.write("                    <i class=\"fab fa-twitter c-icon\"></i>\r\n");
      out.write("                    <i class=\"fab fa-google-plus-g c-icon\"></i>\r\n");
      out.write("                    <i class=\"fab fa-youtube c-icon\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"fotter\">@copyright by Ryhty</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Script js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("        integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
